import { Workshop, Student, Registration } from './types';

export const mockWorkshops: Workshop[] = [
  {
    id: '1',
    title: 'Advanced React Patterns',
    description: 'Master advanced React patterns and optimization techniques to build scalable applications.',
    instructor: 'Dr. Sarah Chen',
    category: 'Web Development',
    date: '2024-05-15',
    time: '14:00 - 16:00',
    location: 'Innovation Hub 201',
    capacity: 30,
    registered: 24,
    level: 'Advanced',
    price: 49,
    image: 'https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=400&h=300&fit=crop',
    aiSummary: 'This workshop covers custom hooks, render optimization, suspense patterns, and concurrent React features.',
    syllabus: 'Custom Hooks | Code Splitting | Suspense | Concurrent Features',
    tags: ['React', 'JavaScript', 'Performance'],
  },
  {
    id: '2',
    title: 'Data Science with Python',
    description: 'Learn data analysis and machine learning fundamentals using Python and popular libraries.',
    instructor: 'Prof. James Kumar',
    category: 'Data Science',
    date: '2024-05-18',
    time: '10:00 - 12:00',
    location: 'Science Building 305',
    capacity: 25,
    registered: 22,
    level: 'Intermediate',
    price: 39,
    image: 'https://images.unsplash.com/photo-1526374965328-7f5ae4e8b08f?w=400&h=300&fit=crop',
    aiSummary: 'Introduction to pandas, numpy, and scikit-learn with hands-on projects in data analysis and machine learning.',
    syllabus: 'Pandas Basics | Data Visualization | ML Fundamentals | Case Studies',
    tags: ['Python', 'Data Science', 'Machine Learning'],
  },
  {
    id: '3',
    title: 'UI/UX Design Fundamentals',
    description: 'Create beautiful and functional user interfaces with design principles and modern tools.',
    instructor: 'Emma Rodriguez',
    category: 'Design',
    date: '2024-05-20',
    time: '15:00 - 17:00',
    location: 'Design Studio 102',
    capacity: 20,
    registered: 18,
    level: 'Beginner',
    price: 29,
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=300&fit=crop',
    aiSummary: 'Learn design thinking, color theory, typography, and prototyping using Figma and modern design tools.',
    syllabus: 'Design Thinking | Color Theory | Figma Basics | Prototyping',
    tags: ['Design', 'UI/UX', 'Figma'],
  },
  {
    id: '4',
    title: 'Cloud Architecture with AWS',
    description: 'Build scalable cloud solutions using Amazon Web Services and modern DevOps practices.',
    instructor: 'Michael Zhang',
    category: 'Cloud Computing',
    date: '2024-05-22',
    time: '09:00 - 11:00',
    location: 'Tech Building 401',
    capacity: 28,
    registered: 15,
    level: 'Advanced',
    price: 59,
    image: 'https://images.unsplash.com/photo-1516321318423-f06f70504504?w=400&h=300&fit=crop',
    aiSummary: 'EC2, S3, RDS, Lambda, and containerization with Docker. Real-world deployment scenarios included.',
    syllabus: 'AWS Services | Docker & Kubernetes | CI/CD | Infrastructure as Code',
    tags: ['AWS', 'DevOps', 'Cloud'],
  },
  {
    id: '5',
    title: 'Mobile App Development with React Native',
    description: 'Build native mobile applications for iOS and Android using React Native framework.',
    instructor: 'Lisa Wang',
    category: 'Mobile Development',
    date: '2024-05-25',
    time: '13:00 - 15:00',
    location: 'Tech Building 201',
    capacity: 22,
    registered: 19,
    level: 'Intermediate',
    price: 44,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop',
    aiSummary: 'React Native fundamentals, navigation, state management, and publishing to app stores.',
    syllabus: 'React Native Basics | Navigation | State Management | App Publishing',
    tags: ['React Native', 'Mobile', 'JavaScript'],
  },
  {
    id: '6',
    title: 'Cybersecurity Essentials',
    description: 'Understand security principles, common vulnerabilities, and best practices for protecting systems.',
    instructor: 'Dr. Robert Miles',
    category: 'Security',
    date: '2024-05-27',
    time: '11:00 - 13:00',
    location: 'Science Building 202',
    capacity: 25,
    registered: 12,
    level: 'Beginner',
    price: 34,
    image: 'https://images.unsplash.com/photo-1515378960830-ce8aca4d8e60?w=400&h=300&fit=crop',
    aiSummary: 'Network security, cryptography basics, vulnerability assessment, and secure coding practices.',
    syllabus: 'Network Security | Cryptography | Threat Analysis | Secure Coding',
    tags: ['Security', 'Cybersecurity', 'IT'],
  },
];

export const mockStudents: Student[] = [
  {
    id: '101',
    name: 'Alex Johnson',
    email: 'alex.johnson@university.edu',
    university: 'State University',
    major: 'Computer Science',
    registeredWorkshops: ['1', '2'],
  },
  {
    id: '102',
    name: 'Jessica Lee',
    email: 'jessica.lee@university.edu',
    university: 'State University',
    major: 'Information Technology',
    registeredWorkshops: ['3', '4', '5'],
  },
  {
    id: '103',
    name: 'Marcus Thompson',
    email: 'marcus.thompson@university.edu',
    university: 'State University',
    major: 'Data Science',
    registeredWorkshops: ['2'],
  },
];

export const mockRegistrations: Registration[] = [
  {
    id: 'reg1',
    studentId: '101',
    workshopId: '1',
    registeredAt: '2024-04-20T10:30:00Z',
    status: 'active',
  },
  {
    id: 'reg2',
    studentId: '101',
    workshopId: '2',
    registeredAt: '2024-04-21T14:15:00Z',
    status: 'active',
  },
  {
    id: 'reg3',
    studentId: '102',
    workshopId: '3',
    registeredAt: '2024-04-19T09:00:00Z',
    status: 'active',
  },
  {
    id: 'reg4',
    studentId: '102',
    workshopId: '4',
    registeredAt: '2024-04-22T11:45:00Z',
    status: 'active',
  },
  {
    id: 'reg5',
    studentId: '102',
    workshopId: '5',
    registeredAt: '2024-04-23T16:20:00Z',
    status: 'active',
  },
  {
    id: 'reg6',
    studentId: '103',
    workshopId: '2',
    registeredAt: '2024-04-18T13:30:00Z',
    status: 'active',
  },
];
